spring:
  datasource:
    username: pos
    password: xieRONGkun12138
    url: jdbc:mysql://rm-bp11qa0y559ke1v79lo.mysql.rds.aliyuncs.com:3306/pos?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.pos.posdataintroduction.domain

#showSql
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      root: info  #日志配置DEBUG,INFO,WARN,  ERROR
      security: debug
      example:
        mapper : debug
  file:
    path: F:\projects\postdataintroduction\logs

